export const MOCK_CARDS = [
    {
        _id: '1',
        name: 'HTML',
        logo:'assets/HTML.png',
        reviews: 15,
        score: 4.066666,
    },
    {
        _id: '2',
        name: 'CSS',
        logo: 'assets/CSS.png',
        reviews: 4,
        score: 3.5,
    },
    {
        _id: '3',
        name: 'JavaScript',
        logo: 'assets/JS.png',
        reviews: 2,
        score: 3,
    },
    {
        _id: '4',
        name: 'Node',
        logo: 'assets/Node.png',
        reviews: 0,
        score: 0,
    },
    {
        _id: '5',
        name: 'TypeScript',
        logo: 'assets/TypeScript.png',
        reviews: 0,
        score: 0,
    },
    {
        _id: '6',
        name: 'PostgreSQL',
        logo: 'assets/PostgreSQL.png',
        reviews: 1,
        score: 5,
    },
    {
        _id: '7',
        name: 'MongoDB',
        logo: 'assets/MongoDB.png',
        reviews: 0,
        score: 0,
    },
]